"""C source generation through ``cantools generate_c_source``."""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Dict, List

# The header comment carries the cantools version and a timestamp.
_STAMP_RE = re.compile(r"generated by cantools version .*")


def _body(text: str) -> str:
    return _STAMP_RE.sub("generated by cantools", text)


def generate(dbc_path: Path, output_dir: Path, dry_run: bool = False) -> Dict[str, List[str]]:
    """Generates into a temp dir, then copies files whose content changed.

    A file that differs only in the version and date stamp is left alone, so
    regenerating an unchanged DBC leaves git clean.
    """
    dbc_path, output_dir = Path(dbc_path), Path(output_dir)
    result = {"changed": [], "unchanged": [], "created": []}
    with tempfile.TemporaryDirectory() as tmp:
        cmd = [sys.executable, "-m", "cantools", "generate_c_source",
               str(dbc_path), "-o", tmp]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            raise RuntimeError(proc.stderr.strip() or proc.stdout.strip()
                               or "cantools generate_c_source failed")
        for produced in sorted(Path(tmp).iterdir()):
            target = output_dir / produced.name
            new = produced.read_text(encoding="utf-8")
            if target.exists():
                old = target.read_text(encoding="utf-8")
                if _body(old) == _body(new):
                    result["unchanged"].append(str(target))
                    continue
                result["changed"].append(str(target))
            else:
                result["created"].append(str(target))
            if not dry_run:
                output_dir.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(produced, target)
    return result
